### ISSUE TITLE
Is there any way to make this work on exported statics?

### ISSUE THREAD

**Issue by jgarmar** [taddison/next-password-protect-sample#2]
It works on development but when I export the site it doesn't works, doesn't have access to cookie. Thanks

**Comment by taddison** [comment]
Good question! Unfortunately password protection like this won't work with a static site as we need every request to be processed by the server (is the request supposed to see this content or not?).

If you haven't seen already I posted about this solution here https://tjaddison.com/blog/2020/06/password-protect-a-nextjs-site-deployed-to-vercel/ 

I can see now the blog and example don't clearly state it won't work with static sites, will see where I can add that caveat in.

**Comment by utkarshdubey** [comment]
Hey! Any work-around for this?

**Comment by taddison** [comment]
Afraid not - but for alternatives and an explanation of why there is no workaround this blog post by Nis Bornoe is great: https://bornoe.org/blog/2020/05/password-protecting-static-sites/

**Comment by utkarshdubey** [comment]
I managed a workaround through localStorge, pretty inefficient atm but looking to optimize.
